### ISSUE TITLE
5.0.0 release notes missing information on breaking changes

### ISSUE THREAD

**Issue by developher-net** [headcr4sh/node-maven#31]
Major releases indicate breaking changes, yet the changelog doesn't explain what breaks in v5.0.0

This makes it very difficult to assess whether my projects can safely update to 5.0.0

**Comment by headcr4sh** [comment]
You are right. The new major version was a mistake.

I was looking through the changes and created a new versioj, because the method signature of the maven invocation changed. I didn't check carefully enough, otherwise it would have been obvious immediately that the new *optional* parameter didn't introduce a breaking change.

My bad...
... a note in the release notes would be nice, I suppose. I'll keep this ticket open until the CHANGELOG.md has been updated.

**Comment by headcr4sh** [comment]
I just figured out that no CHANGELOG.md is present in this project. Very curious... I have updated the GitHub releases page and added information concerning the non-existing breaking changes in v5.0.0.

Closing this issue.

**Comment by developher-net** [comment]
@headcr4sh thanks for getting back on this - but on closer investigation of the changes you do have a breaking change - an explicit bump of the minimum NodeJS requirement from `v4.0` to `v12.0` in the `engines` field of `package.json`

**Comment by headcr4sh** [comment]
Uh. Yes.. you *are* right. That change though, was not intended and necessary.
